ifeq ($(strip $(llt_gcov)),y)
GCOV_PROFILE := y
endif

obj-y	+= diag_acore_common.o
obj-y	+= diag_api.o
obj-y	+= diag_cfg.o
obj-y	+= diag_debug.o
obj-y	+= diag_fs_proc.o
obj-y	+= diag_message.o
obj-y	+= diag_msgapplog.o
obj-y	+= diag_msgbbp.o
obj-y	+= diag_msgbsp.o
obj-y	+= diag_msghifi.o
obj-y	+= diag_msgmsp.o
obj-y	+= diag_msgphy.o
obj-y	+= diag_msgps.o
obj-y	+= diag_service.o
