#include "ChrCommConvert.h"
#include "ChrEventIDComm.h"

enum STRUCT_ID_ENUM
{
    CAS_1X_RADIO_RESOURCE_CHECK_CHR_RPT_STRU_SUBEVENT	= 98,
    CAS_HRPD_RADIO_RESOURCE_CHECK_CHR_RPT_STRU_SUBEVENT	= 100,
    CAS_RESOURCE_EXCEPTION_INFO_STRU_ID	= 101,
    CTTF_RADIO_RESOURCE_CHECK_CHR_DIRECT_RPT_STRU_SUBEVENT	= 97,
    GAS_CUSTOM_C1_CELL_CHR_RPT_STRU_SUBEVENT	= 76,
    GAS_ERR_LOG_AREA_IDENTIFICATION_STRU_ID	= 81,
    GAS_ERR_LOG_EVT_NET_WORK_FEATURE_RPT_STRU_SUBEVENT	= 78,
    GAS_ERR_LOG_GSM_CELL_INFO_STRU_ID	= 80,
    GAS_MNTN_CUSTOM_C1_CELL_INFO_STRU_ID	= 77,
    GAS_MNTN_GSM_CELL_WITH_AREA_IDENTIFY_STRU_ID	= 79,
    GAS_MNTN_RSRC_CHECK_EXCP_TASK_INFO_STRU_ID	= 103,
    GAS_MNTN_RSRC_CHECK_EXCP_TASK_TYPE_STRU_ID	= 104,
    GAS_NOT_SUPP_BSS_PAGING_COOR_CHR_RPT_STRU_SUBEVENT	= 72,
    GAS_RADIO_RESOURCE_CHECK_CHR_RPT_STRU_SUBEVENT	= 102,
    GUCNAS_RADIO_RESOURCE_CHECK_CHR_RPT_STRU_SUBEVENT	= 95,
    GUCNAS_RESOURCE_CHECK_SESSION_INFO_STRU_ID	= 96,
    GUCNAS_SS_DECODE_EXCEPT_CHR_RPT_STRU_SUBEVENT	= 208,
    LL2_OM_VOLTE_STAT_INFO_STRU_ID	= 144,
    LMAC_OM_PRACH_CONFIG_STRU_ID	= 137,
    LMAC_OM_PREAMBLE_SPEC_NOT_MATCH_INFO_STRU_SUBEVENT	= 133,
    LNAS_EMM_ERR_INFO_3440_TIMEOUT_DO_NOT_REL_STRU_SUBEVENT	= 163,
    LNAS_EMM_ERR_INFO_ATT_FAIL_ESM_NEED_DISABLE_LTE_STRU_SUBEVENT	= 183,
    LNAS_EMM_ERR_INFO_AUTH_REJ_OPT_STRU_SUBEVENT	= 197,
    LNAS_EMM_ERR_INFO_CNMSG_DECODE_FAIL_STRU_SUBEVENT	= 170,
    LNAS_EMM_ERR_INFO_CSFB_TAU_RCV_MT_DETACH_STRU_SUBEVENT	= 203,
    LNAS_EMM_ERR_INFO_DETACH_NO_RF_STRU_SUBEVENT	= 191,
    LNAS_EMM_ERR_INFO_DSDS_BUFFER_NO_RF_TAU_REQ_STRU_SUBEVENT	= 207,
    LNAS_EMM_ERR_INFO_DSDS_NO_RF_TAU_PUNISH_STRU_SUBEVENT	= 206,
    LNAS_EMM_ERR_INFO_DSDS_RF_RECOVER_RETRY_STRU_SUBEVENT	= 155,
    LNAS_EMM_ERR_INFO_DSDS_RRM_RF_CHECKIN_STRU_SUBEVENT	= 149,
    LNAS_EMM_ERR_INFO_EMC_BERER_CN_REJ_ANYCELL_SRCH_STRU_SUBEVENT	= 201,
    LNAS_EMM_ERR_INFO_EMC_DATA_REQ_TAU_STRU_SUBEVENT	= 200,
    LNAS_EMM_ERR_INFO_GRADUAL_FORBIDDEN_OPTIMIZE_STRU_SUBEVENT	= 156,
    LNAS_EMM_ERR_INFO_IMPROVE_CALL_SUCC_RATIO_STRU_SUBEVENT	= 195,
    LNAS_EMM_ERR_INFO_IMS_BEARER_WITH_CN_MOD_CONFLICT_STRU_SUBEVENT	= 162,
    LNAS_EMM_ERR_INFO_LANZHOU_CSFB_OPTIMIZE_STRU_SUBEVENT	= 193,
    LNAS_EMM_ERR_INFO_LOAD_BALANCE_STRU_SUBEVENT	= 154,
    LNAS_EMM_ERR_INFO_LOCAL_DETACH_STRU_SUBEVENT	= 178,
    LNAS_EMM_ERR_INFO_LTE_FAKE_NODEB_STRU_SUBEVENT	= 150,
    LNAS_EMM_ERR_INFO_MMC_REL_DRGINIT_STRU_SUBEVENT	= 184,
    LNAS_EMM_ERR_INFO_MO_BAR_ATTAMPT_STRU_SUBEVENT	= 185,
    LNAS_EMM_ERR_INFO_MT_DETACH_OPTIMIZE_STRU_SUBEVENT	= 204,
    LNAS_EMM_ERR_INFO_MT_SERVICE_RETRY_STRU_SUBEVENT	= 205,
    LNAS_EMM_ERR_INFO_NO_RAU_WITH_TAU_STRU_SUBEVENT	= 161,
    LNAS_EMM_ERR_INFO_PERIODIC_TAU_WITH_CAUSE_STRU_SUBEVENT	= 192,
    LNAS_EMM_ERR_INFO_SMC_FAIL_STRU_SUBEVENT	= 174,
    LNAS_EMM_ERR_INFO_START_3402_ADD_FORB_LIST_STRU_SUBEVENT	= 194,
    LNAS_EMM_ERR_INFO_T3402_DEACTIVED_STRU_SUBEVENT	= 179,
    LNAS_EMM_ERR_INFO_TAU_EST_WITH_CELL_SEARCHING_OPT_STRU_SUBEVENT	= 196,
    LNAS_EMM_ERR_INFO_TAU_WITH_CONN_REL_DO_NOT_WAIT_3411_TIMEOUT_STRU_SUBEVENT	= 198,
    LNAS_EMM_ERR_INFO_VOLTE_WITH_TA_CHANGE_STRU_SUBEVENT	= 160,
    LNAS_ESM_ERR_INFO_CNMSG_DECODE_FAIL_STRU_SUBEVENT	= 187,
    LNAS_ESM_ERR_INFO_ESM_MSG_RETRANSMITE_STRU_SUBEVENT	= 199,
    LNAS_ESM_ERR_INFO_SWITCH_APN_STRU_SUBEVENT	= 186,
    LNAS_IMSA_ERR_INFO_DSDS_SMS_RF_OCCUPY_STRU_SUBEVENT	= 166,
    LNAS_IMSA_ERR_INFO_DSDS_WAIT_BEAR_REL_TIMEOUT_STRU_SUBEVENT	= 165,
    LNAS_IMSA_ERR_INFO_EMC_TCALL_TIMEOUT_STRU_SUBEVENT	= 164,
    LNAS_IMSA_ERR_INFO_HANDOVER_INITIAL_PDN_CONN_STRU_SUBEVENT	= 168,
    LNAS_IMSA_ERR_INFO_REG_REJ_WAIT_RECOVERY_STRU_SUBEVENT	= 169,
    LNAS_IMSA_ERR_INFO_WAIT_RETRY_START_SWITCH_STRU_SUBEVENT	= 167,
    LNAS_OM_ERRLOG_CSS_BAND_LIST_INFO_STRU_SUBEVENT	= 202,
    LNAS_OM_ERRLOG_PLMN_ID_STRU_ID	= 189,
    LNAS_OM_ERRLOG_POSITION_INFO_STRU_ID	= 188,
    LNAS_OM_ERRLOG_TAC_STRU_ID	= 190,
    LPS_LOW_QUILITY_ABNORMAL_STRU_ID	= 140,
    LPS_OM_VOLTE_FAULT_AUTOAN_INFO_STRU_SUBEVENT	= 138,
    LPS_OM_VOLTE_GENERAL_STAT_INFO_STRU_SUBEVENT	= 145,
    LRRC_CHR_DSDS_TASK_TYPE_INFO_STRU_ID	= 113,
    LRRC_CHR_RRM_RES_CHECK_INFO_LIST_STRU_SUBEVENT	= 111,
    LRRC_CHR_RRM_RES_CHECK_INFO_STRU_ID	= 112,
    LRRC_OM_AIR_SIGNAL_INFO_STRU_ID	= 141,
    LRRC_OM_LAYER_EVENT_INFO_STRU_ID	= 142,
    LRRC_OM_MEASRPT_INFO_ID	= 143,
    LRRC_OM_SCELL_ID_ID	= 135,
    LRRC_OM_TAC_STRU_ID	= 147,
    LRRC_OM_UE_CAP_FALL_REPORT_STRU_SUBEVENT	= 127,
    LRRC_OM_USER_PLANE_ERR_REL_REPORT_STRU_SUBEVENT	= 130,
    LRRC_OM_VOLTE_SINGLE_CALL_INFO_STRU_ID	= 146,
    LRRC_OM_VOLTE_SINGLE_FAULT_INFO_STRU_ID	= 148,
    NAS_MM_LAC_STRU_ID	= 152,
    NAS_MM_PLMN_ID_STRU_ID	= 151,
    NAS_MM_TAC_STRU_ID	= 153,
    PCH_CELL_INFO_REPORT_STRU_ID	= 125,
    TAF_SSA_DECODE_FAIL_INFO_STRU_ID	= 209,
    TLL2_LMAC_PREAMBLE_SPEC_NOT_MATCH_LOG_STRU_ID	= 134,
    TLL2_OOS_INFO_STRU_SUBEVENT	= 71,
    TRRC_APP_COLLECT_TDS_FREQ_REPORT_STRU_SUBEVENT	= 115,
    TRRC_APP_CONFIG_PCH_CELL_INFO_REPORT_STRU_SUBEVENT	= 124,
    TRRC_APP_CS_RELEASE_CELL_INFO_STRU_ID	= 122,
    TRRC_APP_STATE_INFO_STRU_ID	= 121,
    TRRC_CHR_DSDS_TASK_TYPE_INFO_STRU_ID	= 110,
    TRRC_CHR_RRM_RESOURCE_CHECK_INFO_LIST_STRU_SUBEVENT	= 108,
    TRRC_CHR_RRM_RESOURCE_CHECK_INFO_STRU_ID	= 109,
    TRRC_CS_CALL_AIRMSG_INFO_STRU_SUBEVENT	= 120,
    TRRC_CS_CALL_CONN_REQ_INFO_STRU_SUBEVENT	= 117,
    TRRC_CS_CALL_EST_CNF_INFO_STRU_SUBEVENT	= 116,
    TRRC_CS_CALL_MM_INFO_STRU_ID	= 123,
    TRRC_OOS_INFO_STRU_SUBEVENT	= 70,
    TRRC_OUT_OF_SYNC_CELL_UPDATE_INFO_STRU_SUBEVENT	= 114,
    T_CellDesc_Tag_ID	= 126,
    WAS_MNTN_ERR_LOG_ACCESS_LONG_INFO_STRU_ID	= 83,
    WAS_MNTN_ERR_LOG_ACCESS_POWER_INFO_STRU_ID	= 86,
    WAS_MNTN_ERR_LOG_RESOURCE_CHECK_EXCEPTION_INFO_STRU_ID	= 106,
    WAS_MNTN_ERR_LOG_RRM_PS_TASK_TYPE_INFO_STRU_ID	= 107,
    WAS_MNTN_ERR_LOG_SERV_CELL_INFO_STRU_ID	= 94,
    WAS_MNTN_ERR_LOG_SERV_CELL_WHOLE_INFO_STRU_ID	= 93,
    WAS_MNTN_ERR_LOG_W2W_RESEL_SLOW_INFO_STRU_ID	= 91,
    WAS_MNTN_ERR_LOG_WOOS_SRCH_SECTION_INFO_STRU_ID	= 89,
    WAS_NET_WORK_FEATURE_CHR_RPT_STRU_SUBEVENT	= 92,
    WAS_RADIO_RESOURCE_CHECK_CHR_RPT_STRU_SUBEVENT	= 105,
    WAS_RRC_ACCESS_LONG_CHR_RPT_STRU_SUBEVENT	= 82,
    WAS_RRC_STATE_LAST_TIME_CHR_RPT_STRU_SUBEVENT	= 87,
    WAS_W2W_RESEL_SLOW_CHR_RPT_STRU_SUBEVENT	= 90,
    WAS_WOOS_SEARCH_SECTION_CHR_RPT_STRU_SUBEVENT	= 88,
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[5];
} g_CAS_1X_RADIO_RESOURCE_CHECK_CHR_RPT_STRU = 
{
    CAS_1X_RADIO_RESOURCE_CHECK_CHR_RPT_STRU_ALARMID,     CAS_1X_RADIO_RESOURCE_CHECK_CHR_RPT_STRU_SUBEVENT,     136,     5,
    {
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_ENUM, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_ARRAY, 2},
    {0x1000 | FIELD_TYPE_CLASSARRAY, CAS_RESOURCE_EXCEPTION_INFO_STRU_ID},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[5];
} g_CAS_HRPD_RADIO_RESOURCE_CHECK_CHR_RPT_STRU = 
{
    CAS_HRPD_RADIO_RESOURCE_CHECK_CHR_RPT_STRU_ALARMID,     CAS_HRPD_RADIO_RESOURCE_CHECK_CHR_RPT_STRU_SUBEVENT,     136,     5,
    {
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_ENUM, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_ARRAY, 2},
    {0x1000 | FIELD_TYPE_CLASSARRAY, CAS_RESOURCE_EXCEPTION_INFO_STRU_ID},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[6];
} g_CTTF_RADIO_RESOURCE_CHECK_CHR_DIRECT_RPT_STRU = 
{
    CTTF_RADIO_RESOURCE_CHECK_CHR_DIRECT_RPT_STRU_ALARMID,     CTTF_RADIO_RESOURCE_CHECK_CHR_DIRECT_RPT_STRU_SUBEVENT,     16,     6,
    {
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_ARRAY, 1},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[3];
} g_GAS_CUSTOM_C1_CELL_CHR_RPT_STRU = 
{
    GAS_CUSTOM_C1_CELL_CHR_RPT_STRU_ALARMID,     GAS_CUSTOM_C1_CELL_CHR_RPT_STRU_SUBEVENT,     164,     3,
    {
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_ARRAY, 3},
    {0xA00 | FIELD_TYPE_CLASSARRAY, GAS_MNTN_CUSTOM_C1_CELL_INFO_STRU_ID},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[3];
} g_GAS_ERR_LOG_EVT_NET_WORK_FEATURE_RPT_STRU = 
{
    GAS_ERR_LOG_EVT_NET_WORK_FEATURE_RPT_STRU_ALARMID,     GAS_ERR_LOG_EVT_NET_WORK_FEATURE_RPT_STRU_SUBEVENT,     28,     3,
    {
    {FIELD_TYPE_ENUM, 2},
    {FIELD_TYPE_ARRAY, 2},
    {FIELD_TYPE_CLASS, GAS_MNTN_GSM_CELL_WITH_AREA_IDENTIFY_STRU_ID},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[3];
} g_GAS_NOT_SUPP_BSS_PAGING_COOR_CHR_RPT_STRU = 
{
    GAS_NOT_SUPP_BSS_PAGING_COOR_CHR_RPT_STRU_ALARMID,     GAS_NOT_SUPP_BSS_PAGING_COOR_CHR_RPT_STRU_SUBEVENT,     244,     3,
    {
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_ARRAY, 3},
    {0xA00 | FIELD_TYPE_CLASSARRAY, GAS_MNTN_GSM_CELL_WITH_AREA_IDENTIFY_STRU_ID},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[3];
} g_GAS_RADIO_RESOURCE_CHECK_CHR_RPT_STRU = 
{
    GAS_RADIO_RESOURCE_CHECK_CHR_RPT_STRU_ALARMID,     GAS_RADIO_RESOURCE_CHECK_CHR_RPT_STRU_SUBEVENT,     106,     3,
    {
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_ARRAY, 3},
    {0x300 | FIELD_TYPE_CLASSARRAY, GAS_MNTN_RSRC_CHECK_EXCP_TASK_INFO_STRU_ID},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[3];
} g_GAS_STATISTIC_INFO_COLLECTION = 
{
    GAS_STATISTIC_INFO_COLLECTION_EVENTID,     0,     436,     3,
    {
    {FIELD_TYPE_CLASS, GAS_NOT_SUPP_BSS_PAGING_COOR_CHR_RPT_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, GAS_CUSTOM_C1_CELL_CHR_RPT_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, GAS_ERR_LOG_EVT_NET_WORK_FEATURE_RPT_STRU_SUBEVENT},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[1];
} g_GUCNAS_RADIO_RESOURCE_CHECK_CHR_RPT_STRU = 
{
    GUCNAS_RADIO_RESOURCE_CHECK_CHR_RPT_STRU_ALARMID,     GUCNAS_RADIO_RESOURCE_CHECK_CHR_RPT_STRU_SUBEVENT,     304,     1,
    {
    {0x2600 | FIELD_TYPE_CLASSARRAY, GUCNAS_RESOURCE_CHECK_SESSION_INFO_STRU_ID},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[3];
} g_GUCNAS_SS_DECODE_EXCEPT_CHR_RPT_STRU = 
{
    GUCNAS_SS_DECODE_EXCEPT_CHR_RPT_STRU_ALARMID,     GUCNAS_SS_DECODE_EXCEPT_CHR_RPT_STRU_SUBEVENT,     164,     3,
    {
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_ARRAY, 3},
    {0x1400 | FIELD_TYPE_CLASSARRAY, TAF_SSA_DECODE_FAIL_INFO_STRU_ID},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[1];
} g_GUCNAS_STATISTIC_INFO_COLLECTION = 
{
    GUCNAS_STATISTIC_INFO_COLLECTION_EVENTID,     0,     164,     1,
    {
    {FIELD_TYPE_CLASS, GUCNAS_SS_DECODE_EXCEPT_CHR_RPT_STRU_SUBEVENT},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[1];
} g_LL2_STATISTIC_INFO_COLLECTION = 
{
    LL2_STATISTIC_INFO_COLLECTION_EVENTID,     0,     260,     1,
    {
    {FIELD_TYPE_CLASS, LMAC_OM_PREAMBLE_SPEC_NOT_MATCH_INFO_STRU_SUBEVENT},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[3];
} g_LMAC_OM_PREAMBLE_SPEC_NOT_MATCH_INFO_STRU = 
{
    LMAC_OM_PREAMBLE_SPEC_NOT_MATCH_INFO_STRU_ALARMID,     LMAC_OM_PREAMBLE_SPEC_NOT_MATCH_INFO_STRU_SUBEVENT,     260,     3,
    {
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_ARRAY, 3},
    {0x800 | FIELD_TYPE_CLASSARRAY, TLL2_LMAC_PREAMBLE_SPEC_NOT_MATCH_LOG_STRU_ID},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[1];
} g_LNAS_EMM_ERR_INFO_3440_TIMEOUT_DO_NOT_REL_STRU = 
{
    LNAS_EMM_ERR_INFO_3440_TIMEOUT_DO_NOT_REL_STRU_ALARMID,     LNAS_EMM_ERR_INFO_3440_TIMEOUT_DO_NOT_REL_STRU_SUBEVENT,     4,     1,
    {
    {FIELD_TYPE_UINT, 4},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[1];
} g_LNAS_EMM_ERR_INFO_ATT_FAIL_ESM_NEED_DISABLE_LTE_STRU = 
{
    LNAS_EMM_ERR_INFO_ATT_FAIL_ESM_NEED_DISABLE_LTE_STRU_ALARMID,     LNAS_EMM_ERR_INFO_ATT_FAIL_ESM_NEED_DISABLE_LTE_STRU_SUBEVENT,     4,     1,
    {
    {FIELD_TYPE_ENUM, 4},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[2];
} g_LNAS_EMM_ERR_INFO_AUTH_REJ_OPT_STRU = 
{
    LNAS_EMM_ERR_INFO_AUTH_REJ_OPT_STRU_ALARMID,     LNAS_EMM_ERR_INFO_AUTH_REJ_OPT_STRU_SUBEVENT,     4,     2,
    {
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[4];
} g_LNAS_EMM_ERR_INFO_CNMSG_DECODE_FAIL_STRU = 
{
    LNAS_EMM_ERR_INFO_CNMSG_DECODE_FAIL_STRU_ALARMID,     LNAS_EMM_ERR_INFO_CNMSG_DECODE_FAIL_STRU_SUBEVENT,     60,     4,
    {
    {FIELD_TYPE_ENUM, 4},
    {FIELD_TYPE_ENUM, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_CLASS, LNAS_OM_ERRLOG_POSITION_INFO_STRU_ID},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[1];
} g_LNAS_EMM_ERR_INFO_CSFB_TAU_RCV_MT_DETACH_STRU = 
{
    LNAS_EMM_ERR_INFO_CSFB_TAU_RCV_MT_DETACH_STRU_ALARMID,     LNAS_EMM_ERR_INFO_CSFB_TAU_RCV_MT_DETACH_STRU_SUBEVENT,     4,     1,
    {
    {FIELD_TYPE_UINT, 4},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[2];
} g_LNAS_EMM_ERR_INFO_DETACH_NO_RF_STRU = 
{
    LNAS_EMM_ERR_INFO_DETACH_NO_RF_STRU_ALARMID,     LNAS_EMM_ERR_INFO_DETACH_NO_RF_STRU_SUBEVENT,     8,     2,
    {
    {FIELD_TYPE_ENUM, 4},
    {FIELD_TYPE_ENUM, 4},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[1];
} g_LNAS_EMM_ERR_INFO_DSDS_BUFFER_NO_RF_TAU_REQ_STRU = 
{
    LNAS_EMM_ERR_INFO_DSDS_BUFFER_NO_RF_TAU_REQ_STRU_ALARMID,     LNAS_EMM_ERR_INFO_DSDS_BUFFER_NO_RF_TAU_REQ_STRU_SUBEVENT,     4,     1,
    {
    {FIELD_TYPE_UINT, 4},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[1];
} g_LNAS_EMM_ERR_INFO_DSDS_NO_RF_TAU_PUNISH_STRU = 
{
    LNAS_EMM_ERR_INFO_DSDS_NO_RF_TAU_PUNISH_STRU_ALARMID,     LNAS_EMM_ERR_INFO_DSDS_NO_RF_TAU_PUNISH_STRU_SUBEVENT,     4,     1,
    {
    {FIELD_TYPE_UINT, 4},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[2];
} g_LNAS_EMM_ERR_INFO_DSDS_RF_RECOVER_RETRY_STRU = 
{
    LNAS_EMM_ERR_INFO_DSDS_RF_RECOVER_RETRY_STRU_ALARMID,     LNAS_EMM_ERR_INFO_DSDS_RF_RECOVER_RETRY_STRU_SUBEVENT,     4,     2,
    {
    {FIELD_TYPE_ENUM, 2},
    {FIELD_TYPE_ENUM, 2},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[2];
} g_LNAS_EMM_ERR_INFO_DSDS_RRM_RF_CHECKIN_STRU = 
{
    LNAS_EMM_ERR_INFO_DSDS_RRM_RF_CHECKIN_STRU_ALARMID,     LNAS_EMM_ERR_INFO_DSDS_RRM_RF_CHECKIN_STRU_SUBEVENT,     4,     2,
    {
    {FIELD_TYPE_ENUM, 2},
    {FIELD_TYPE_ARRAY, 2},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[1];
} g_LNAS_EMM_ERR_INFO_EMC_BERER_CN_REJ_ANYCELL_SRCH_STRU = 
{
    LNAS_EMM_ERR_INFO_EMC_BERER_CN_REJ_ANYCELL_SRCH_STRU_ALARMID,     LNAS_EMM_ERR_INFO_EMC_BERER_CN_REJ_ANYCELL_SRCH_STRU_SUBEVENT,     4,     1,
    {
    {FIELD_TYPE_UINT, 4},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[1];
} g_LNAS_EMM_ERR_INFO_EMC_DATA_REQ_TAU_STRU = 
{
    LNAS_EMM_ERR_INFO_EMC_DATA_REQ_TAU_STRU_ALARMID,     LNAS_EMM_ERR_INFO_EMC_DATA_REQ_TAU_STRU_SUBEVENT,     4,     1,
    {
    {FIELD_TYPE_UINT, 4},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[5];
} g_LNAS_EMM_ERR_INFO_GRADUAL_FORBIDDEN_OPTIMIZE_STRU = 
{
    LNAS_EMM_ERR_INFO_GRADUAL_FORBIDDEN_OPTIMIZE_STRU_ALARMID,     LNAS_EMM_ERR_INFO_GRADUAL_FORBIDDEN_OPTIMIZE_STRU_SUBEVENT,     60,     5,
    {
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_CLASS, LNAS_OM_ERRLOG_POSITION_INFO_STRU_ID},
    {FIELD_TYPE_ENUM, 1},
    {FIELD_TYPE_ARRAY, 3},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[2];
} g_LNAS_EMM_ERR_INFO_IMPROVE_CALL_SUCC_RATIO_STRU = 
{
    LNAS_EMM_ERR_INFO_IMPROVE_CALL_SUCC_RATIO_STRU_ALARMID,     LNAS_EMM_ERR_INFO_IMPROVE_CALL_SUCC_RATIO_STRU_SUBEVENT,     4,     2,
    {
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_ENUM, 2},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[1];
} g_LNAS_EMM_ERR_INFO_IMS_BEARER_WITH_CN_MOD_CONFLICT_STRU = 
{
    LNAS_EMM_ERR_INFO_IMS_BEARER_WITH_CN_MOD_CONFLICT_STRU_ALARMID,     LNAS_EMM_ERR_INFO_IMS_BEARER_WITH_CN_MOD_CONFLICT_STRU_SUBEVENT,     4,     1,
    {
    {FIELD_TYPE_UINT, 4},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[1];
} g_LNAS_EMM_ERR_INFO_LANZHOU_CSFB_OPTIMIZE_STRU = 
{
    LNAS_EMM_ERR_INFO_LANZHOU_CSFB_OPTIMIZE_STRU_ALARMID,     LNAS_EMM_ERR_INFO_LANZHOU_CSFB_OPTIMIZE_STRU_SUBEVENT,     4,     1,
    {
    {FIELD_TYPE_UINT, 4},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[1];
} g_LNAS_EMM_ERR_INFO_LOAD_BALANCE_STRU = 
{
    LNAS_EMM_ERR_INFO_LOAD_BALANCE_STRU_ALARMID,     LNAS_EMM_ERR_INFO_LOAD_BALANCE_STRU_SUBEVENT,     4,     1,
    {
    {FIELD_TYPE_UINT, 4},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[6];
} g_LNAS_EMM_ERR_INFO_LOCAL_DETACH_STRU = 
{
    LNAS_EMM_ERR_INFO_LOCAL_DETACH_STRU_ALARMID,     LNAS_EMM_ERR_INFO_LOCAL_DETACH_STRU_SUBEVENT,     20,     6,
    {
    {FIELD_TYPE_ENUM, 4},
    {FIELD_TYPE_ENUM, 4},
    {FIELD_TYPE_ENUM, 4},
    {FIELD_TYPE_ENUM, 2},
    {FIELD_TYPE_ENUM, 2},
    {FIELD_TYPE_UINT, 4},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[7];
} g_LNAS_EMM_ERR_INFO_LTE_FAKE_NODEB_STRU = 
{
    LNAS_EMM_ERR_INFO_LTE_FAKE_NODEB_STRU_ALARMID,     LNAS_EMM_ERR_INFO_LTE_FAKE_NODEB_STRU_SUBEVENT,     24,     7,
    {
    {FIELD_TYPE_CLASS, NAS_MM_PLMN_ID_STRU_ID},
    {FIELD_TYPE_CLASS, NAS_MM_LAC_STRU_ID},
    {FIELD_TYPE_CLASS, NAS_MM_TAC_STRU_ID},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_ENUM, 1},
    {FIELD_TYPE_ARRAY, 3},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[1];
} g_LNAS_EMM_ERR_INFO_MMC_REL_DRGINIT_STRU = 
{
    LNAS_EMM_ERR_INFO_MMC_REL_DRGINIT_STRU_ALARMID,     LNAS_EMM_ERR_INFO_MMC_REL_DRGINIT_STRU_SUBEVENT,     4,     1,
    {
    {FIELD_TYPE_ENUM, 4},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[1];
} g_LNAS_EMM_ERR_INFO_MO_BAR_ATTAMPT_STRU = 
{
    LNAS_EMM_ERR_INFO_MO_BAR_ATTAMPT_STRU_ALARMID,     LNAS_EMM_ERR_INFO_MO_BAR_ATTAMPT_STRU_SUBEVENT,     4,     1,
    {
    {FIELD_TYPE_ENUM, 4},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[2];
} g_LNAS_EMM_ERR_INFO_MT_DETACH_OPTIMIZE_STRU = 
{
    LNAS_EMM_ERR_INFO_MT_DETACH_OPTIMIZE_STRU_ALARMID,     LNAS_EMM_ERR_INFO_MT_DETACH_OPTIMIZE_STRU_SUBEVENT,     4,     2,
    {
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_ARRAY, 2},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[3];
} g_LNAS_EMM_ERR_INFO_MT_SERVICE_RETRY_STRU = 
{
    LNAS_EMM_ERR_INFO_MT_SERVICE_RETRY_STRU_ALARMID,     LNAS_EMM_ERR_INFO_MT_SERVICE_RETRY_STRU_SUBEVENT,     12,     3,
    {
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[2];
} g_LNAS_EMM_ERR_INFO_NO_RAU_WITH_TAU_STRU = 
{
    LNAS_EMM_ERR_INFO_NO_RAU_WITH_TAU_STRU_ALARMID,     LNAS_EMM_ERR_INFO_NO_RAU_WITH_TAU_STRU_SUBEVENT,     8,     2,
    {
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[1];
} g_LNAS_EMM_ERR_INFO_PERIODIC_TAU_WITH_CAUSE_STRU = 
{
    LNAS_EMM_ERR_INFO_PERIODIC_TAU_WITH_CAUSE_STRU_ALARMID,     LNAS_EMM_ERR_INFO_PERIODIC_TAU_WITH_CAUSE_STRU_SUBEVENT,     1,     1,
    {
    {FIELD_TYPE_ENUM, 1},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[3];
} g_LNAS_EMM_ERR_INFO_SMC_FAIL_STRU = 
{
    LNAS_EMM_ERR_INFO_SMC_FAIL_STRU_ALARMID,     LNAS_EMM_ERR_INFO_SMC_FAIL_STRU_SUBEVENT,     56,     3,
    {
    {FIELD_TYPE_ENUM, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_CLASS, LNAS_OM_ERRLOG_POSITION_INFO_STRU_ID},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[1];
} g_LNAS_EMM_ERR_INFO_START_3402_ADD_FORB_LIST_STRU = 
{
    LNAS_EMM_ERR_INFO_START_3402_ADD_FORB_LIST_STRU_ALARMID,     LNAS_EMM_ERR_INFO_START_3402_ADD_FORB_LIST_STRU_SUBEVENT,     4,     1,
    {
    {FIELD_TYPE_UINT, 4},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[2];
} g_LNAS_EMM_ERR_INFO_T3402_DEACTIVED_STRU = 
{
    LNAS_EMM_ERR_INFO_T3402_DEACTIVED_STRU_ALARMID,     LNAS_EMM_ERR_INFO_T3402_DEACTIVED_STRU_SUBEVENT,     52,     2,
    {
    {FIELD_TYPE_ENUM, 4},
    {FIELD_TYPE_CLASS, LNAS_OM_ERRLOG_POSITION_INFO_STRU_ID},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[1];
} g_LNAS_EMM_ERR_INFO_TAU_EST_WITH_CELL_SEARCHING_OPT_STRU = 
{
    LNAS_EMM_ERR_INFO_TAU_EST_WITH_CELL_SEARCHING_OPT_STRU_ALARMID,     LNAS_EMM_ERR_INFO_TAU_EST_WITH_CELL_SEARCHING_OPT_STRU_SUBEVENT,     4,     1,
    {
    {FIELD_TYPE_UINT, 4},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[1];
} g_LNAS_EMM_ERR_INFO_TAU_WITH_CONN_REL_DO_NOT_WAIT_3411_TIMEOUT_STRU = 
{
    LNAS_EMM_ERR_INFO_TAU_WITH_CONN_REL_DO_NOT_WAIT_3411_TIMEOUT_STRU_ALARMID,     LNAS_EMM_ERR_INFO_TAU_WITH_CONN_REL_DO_NOT_WAIT_3411_TIMEOUT_STRU_SUBEVENT,     4,     1,
    {
    {FIELD_TYPE_UINT, 4},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[1];
} g_LNAS_EMM_ERR_INFO_VOLTE_WITH_TA_CHANGE_STRU = 
{
    LNAS_EMM_ERR_INFO_VOLTE_WITH_TA_CHANGE_STRU_ALARMID,     LNAS_EMM_ERR_INFO_VOLTE_WITH_TA_CHANGE_STRU_SUBEVENT,     4,     1,
    {
    {FIELD_TYPE_UINT, 4},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[4];
} g_LNAS_ESM_ERR_INFO_CNMSG_DECODE_FAIL_STRU = 
{
    LNAS_ESM_ERR_INFO_CNMSG_DECODE_FAIL_STRU_ALARMID,     LNAS_ESM_ERR_INFO_CNMSG_DECODE_FAIL_STRU_SUBEVENT,     60,     4,
    {
    {FIELD_TYPE_ENUM, 4},
    {FIELD_TYPE_ENUM, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_CLASS, LNAS_OM_ERRLOG_POSITION_INFO_STRU_ID},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[1];
} g_LNAS_ESM_ERR_INFO_ESM_MSG_RETRANSMITE_STRU = 
{
    LNAS_ESM_ERR_INFO_ESM_MSG_RETRANSMITE_STRU_ALARMID,     LNAS_ESM_ERR_INFO_ESM_MSG_RETRANSMITE_STRU_SUBEVENT,     4,     1,
    {
    {FIELD_TYPE_ENUM, 4},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[1];
} g_LNAS_ESM_ERR_INFO_SWITCH_APN_STRU = 
{
    LNAS_ESM_ERR_INFO_SWITCH_APN_STRU_ALARMID,     LNAS_ESM_ERR_INFO_SWITCH_APN_STRU_SUBEVENT,     4,     1,
    {
    {FIELD_TYPE_UINT, 4},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[2];
} g_LNAS_IMSA_ERR_INFO_DSDS_SMS_RF_OCCUPY_STRU = 
{
    LNAS_IMSA_ERR_INFO_DSDS_SMS_RF_OCCUPY_STRU_ALARMID,     LNAS_IMSA_ERR_INFO_DSDS_SMS_RF_OCCUPY_STRU_SUBEVENT,     8,     2,
    {
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[2];
} g_LNAS_IMSA_ERR_INFO_DSDS_WAIT_BEAR_REL_TIMEOUT_STRU = 
{
    LNAS_IMSA_ERR_INFO_DSDS_WAIT_BEAR_REL_TIMEOUT_STRU_ALARMID,     LNAS_IMSA_ERR_INFO_DSDS_WAIT_BEAR_REL_TIMEOUT_STRU_SUBEVENT,     4,     2,
    {
    {FIELD_TYPE_ENUM, 2},
    {FIELD_TYPE_ARRAY, 2},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[2];
} g_LNAS_IMSA_ERR_INFO_EMC_TCALL_TIMEOUT_STRU = 
{
    LNAS_IMSA_ERR_INFO_EMC_TCALL_TIMEOUT_STRU_ALARMID,     LNAS_IMSA_ERR_INFO_EMC_TCALL_TIMEOUT_STRU_SUBEVENT,     8,     2,
    {
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[2];
} g_LNAS_IMSA_ERR_INFO_HANDOVER_INITIAL_PDN_CONN_STRU = 
{
    LNAS_IMSA_ERR_INFO_HANDOVER_INITIAL_PDN_CONN_STRU_ALARMID,     LNAS_IMSA_ERR_INFO_HANDOVER_INITIAL_PDN_CONN_STRU_SUBEVENT,     5,     2,
    {
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_ENUM, 1},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[4];
} g_LNAS_IMSA_ERR_INFO_REG_REJ_WAIT_RECOVERY_STRU = 
{
    LNAS_IMSA_ERR_INFO_REG_REJ_WAIT_RECOVERY_STRU_ALARMID,     LNAS_IMSA_ERR_INFO_REG_REJ_WAIT_RECOVERY_STRU_SUBEVENT,     4,     4,
    {
    {FIELD_TYPE_ENUM, 1},
    {FIELD_TYPE_ENUM, 1},
    {FIELD_TYPE_ENUM, 1},
    {FIELD_TYPE_ARRAY, 1},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[2];
} g_LNAS_IMSA_ERR_INFO_WAIT_RETRY_START_SWITCH_STRU = 
{
    LNAS_IMSA_ERR_INFO_WAIT_RETRY_START_SWITCH_STRU_ALARMID,     LNAS_IMSA_ERR_INFO_WAIT_RETRY_START_SWITCH_STRU_SUBEVENT,     4,     2,
    {
    {FIELD_TYPE_ENUM, 1},
    {FIELD_TYPE_ARRAY, 3},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[24];
} g_LNAS_OM_ERRLOG_CSS_BAND_LIST_INFO_STRU = 
{
    LNAS_OM_ERRLOG_CSS_BAND_LIST_INFO_STRU_ALARMID,     LNAS_OM_ERRLOG_CSS_BAND_LIST_INFO_STRU_SUBEVENT,     48,     24,
    {
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_ARRAY, 3},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[41];
} g_LNAS_STATISTIC_INFO_COLLECTION = 
{
    LNAS_STATISTIC_INFO_COLLECTION_EVENTID,     0,     534,     41,
    {
    {FIELD_TYPE_CLASS, LNAS_EMM_ERR_INFO_DSDS_RRM_RF_CHECKIN_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LNAS_EMM_ERR_INFO_LTE_FAKE_NODEB_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LNAS_EMM_ERR_INFO_LOAD_BALANCE_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LNAS_EMM_ERR_INFO_DSDS_RF_RECOVER_RETRY_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LNAS_EMM_ERR_INFO_GRADUAL_FORBIDDEN_OPTIMIZE_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LNAS_EMM_ERR_INFO_VOLTE_WITH_TA_CHANGE_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LNAS_EMM_ERR_INFO_NO_RAU_WITH_TAU_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LNAS_EMM_ERR_INFO_IMS_BEARER_WITH_CN_MOD_CONFLICT_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LNAS_EMM_ERR_INFO_3440_TIMEOUT_DO_NOT_REL_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LNAS_IMSA_ERR_INFO_EMC_TCALL_TIMEOUT_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LNAS_IMSA_ERR_INFO_DSDS_WAIT_BEAR_REL_TIMEOUT_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LNAS_IMSA_ERR_INFO_DSDS_SMS_RF_OCCUPY_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LNAS_IMSA_ERR_INFO_WAIT_RETRY_START_SWITCH_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LNAS_IMSA_ERR_INFO_HANDOVER_INITIAL_PDN_CONN_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LNAS_IMSA_ERR_INFO_REG_REJ_WAIT_RECOVERY_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LNAS_EMM_ERR_INFO_CNMSG_DECODE_FAIL_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LNAS_EMM_ERR_INFO_SMC_FAIL_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LNAS_EMM_ERR_INFO_LOCAL_DETACH_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LNAS_EMM_ERR_INFO_T3402_DEACTIVED_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LNAS_EMM_ERR_INFO_ATT_FAIL_ESM_NEED_DISABLE_LTE_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LNAS_EMM_ERR_INFO_MMC_REL_DRGINIT_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LNAS_EMM_ERR_INFO_MO_BAR_ATTAMPT_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LNAS_ESM_ERR_INFO_SWITCH_APN_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LNAS_ESM_ERR_INFO_CNMSG_DECODE_FAIL_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LNAS_EMM_ERR_INFO_DETACH_NO_RF_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LNAS_EMM_ERR_INFO_PERIODIC_TAU_WITH_CAUSE_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LNAS_EMM_ERR_INFO_LANZHOU_CSFB_OPTIMIZE_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LNAS_EMM_ERR_INFO_START_3402_ADD_FORB_LIST_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LNAS_EMM_ERR_INFO_IMPROVE_CALL_SUCC_RATIO_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LNAS_EMM_ERR_INFO_TAU_EST_WITH_CELL_SEARCHING_OPT_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LNAS_EMM_ERR_INFO_AUTH_REJ_OPT_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LNAS_EMM_ERR_INFO_TAU_WITH_CONN_REL_DO_NOT_WAIT_3411_TIMEOUT_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LNAS_ESM_ERR_INFO_ESM_MSG_RETRANSMITE_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LNAS_EMM_ERR_INFO_EMC_DATA_REQ_TAU_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LNAS_EMM_ERR_INFO_EMC_BERER_CN_REJ_ANYCELL_SRCH_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LNAS_OM_ERRLOG_CSS_BAND_LIST_INFO_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LNAS_EMM_ERR_INFO_CSFB_TAU_RCV_MT_DETACH_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LNAS_EMM_ERR_INFO_MT_DETACH_OPTIMIZE_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LNAS_EMM_ERR_INFO_MT_SERVICE_RETRY_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LNAS_EMM_ERR_INFO_DSDS_NO_RF_TAU_PUNISH_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LNAS_EMM_ERR_INFO_DSDS_BUFFER_NO_RF_TAU_REQ_STRU_SUBEVENT},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[56];
} g_LPS_OM_VOLTE_FAULT_AUTOAN_INFO_STRU = 
{
    LPS_OM_VOLTE_FAULT_AUTOAN_INFO_STRU_ALARMID,     LPS_OM_VOLTE_FAULT_AUTOAN_INFO_STRU_SUBEVENT,     1712,     56,
    {
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_CLASS, LRRC_OM_TAC_STRU_ID},
    {FIELD_TYPE_ENUM, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_ENUM, 2},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_CLASS, LPS_LOW_QUILITY_ABNORMAL_STRU_ID},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_ENUM, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_ENUM, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {0x1400 | FIELD_TYPE_CLASSARRAY, LRRC_OM_AIR_SIGNAL_INFO_STRU_ID},
    {FIELD_TYPE_UINT, 4},
    {0x3800 | FIELD_TYPE_CLASSARRAY, LRRC_OM_LAYER_EVENT_INFO_STRU_ID},
    {FIELD_TYPE_UINT, 4},
    {0x1000 | FIELD_TYPE_CLASSARRAY, LRRC_OM_MEASRPT_INFO_ID},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {0x600 | FIELD_TYPE_CLASSARRAY, LL2_OM_VOLTE_STAT_INFO_STRU_ID},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[30];
} g_LPS_OM_VOLTE_GENERAL_STAT_INFO_STRU = 
{
    LPS_OM_VOLTE_GENERAL_STAT_INFO_STRU_ALARMID,     LPS_OM_VOLTE_GENERAL_STAT_INFO_STRU_SUBEVENT,     576,     30,
    {
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 4},
    {0x1000 | FIELD_TYPE_CLASSARRAY, LRRC_OM_VOLTE_SINGLE_CALL_INFO_STRU_ID},
    {FIELD_TYPE_UINT, 4},
    {0x2800 | FIELD_TYPE_CLASSARRAY, LRRC_OM_VOLTE_SINGLE_FAULT_INFO_STRU_ID},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[1];
} g_LPS_VOLTE_STAT_IND = 
{
    LPS_VOLTE_STAT_IND_EVENTID,     0,     576,     1,
    {
    {FIELD_TYPE_CLASS, LPS_OM_VOLTE_GENERAL_STAT_INFO_STRU_SUBEVENT},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[3];
} g_LRRC_CHR_RRM_RES_CHECK_INFO_LIST_STRU = 
{
    LRRC_CHR_RRM_RES_CHECK_INFO_LIST_STRU_ALARMID,     LRRC_CHR_RRM_RES_CHECK_INFO_LIST_STRU_SUBEVENT,     724,     3,
    {
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_ARRAY, 2},
    {0xA00 | FIELD_TYPE_CLASSARRAY, LRRC_CHR_RRM_RES_CHECK_INFO_STRU_ID},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[6];
} g_LRRC_OM_UE_CAP_FALL_REPORT_STRU = 
{
    LRRC_OM_UE_CAP_FALL_REPORT_STRU_ALARMID,     LRRC_OM_UE_CAP_FALL_REPORT_STRU_SUBEVENT,     40,     6,
    {
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_ARRAY, 3},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_CLASS, LRRC_OM_SCELL_ID_ID},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[5];
} g_LRRC_OM_USER_PLANE_ERR_REL_REPORT_STRU = 
{
    LRRC_OM_USER_PLANE_ERR_REL_REPORT_STRU_ALARMID,     LRRC_OM_USER_PLANE_ERR_REL_REPORT_STRU_SUBEVENT,     36,     5,
    {
    {FIELD_TYPE_ENUM, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_CLASS, LRRC_OM_SCELL_ID_ID},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[2];
} g_LRRC_STATISTIC1_INFO_COLLECTION = 
{
    LRRC_STATISTIC1_INFO_COLLECTION_EVENTID,     0,     76,     2,
    {
    {FIELD_TYPE_CLASS, LRRC_OM_UE_CAP_FALL_REPORT_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LRRC_OM_USER_PLANE_ERR_REL_REPORT_STRU_SUBEVENT},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[1];
} g_LRRC_VOLTE_FAULT_AUTOAN_IND = 
{
    LRRC_VOLTE_FAULT_AUTOAN_IND_EVENTID,     0,     1712,     1,
    {
    {FIELD_TYPE_CLASS, LPS_OM_VOLTE_FAULT_AUTOAN_INFO_STRU_SUBEVENT},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[8];
} g_PS_RADIO_RESOURCE_CHECK = 
{
    PS_RADIO_RESOURCE_CHECK_EVENTID,     0,     2994,     8,
    {
    {FIELD_TYPE_CLASS, GUCNAS_RADIO_RESOURCE_CHECK_CHR_RPT_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, CTTF_RADIO_RESOURCE_CHECK_CHR_DIRECT_RPT_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, CAS_1X_RADIO_RESOURCE_CHECK_CHR_RPT_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, CAS_HRPD_RADIO_RESOURCE_CHECK_CHR_RPT_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, GAS_RADIO_RESOURCE_CHECK_CHR_RPT_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, WAS_RADIO_RESOURCE_CHECK_CHR_RPT_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, TRRC_CHR_RRM_RESOURCE_CHECK_INFO_LIST_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, LRRC_CHR_RRM_RES_CHECK_INFO_LIST_STRU_SUBEVENT},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[2];
} g_TDS_OOS_INFO_REPORT = 
{
    TDS_OOS_INFO_REPORT_FAULTID,     0,     44,     2,
    {
    {FIELD_TYPE_CLASS, TRRC_OOS_INFO_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, TLL2_OOS_INFO_STRU_SUBEVENT},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[4];
} g_TLL2_OOS_INFO_STRU = 
{
    TLL2_OOS_INFO_STRU_ALARMID,     TLL2_OOS_INFO_STRU_SUBEVENT,     4,     4,
    {
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[50];
} g_TRRC_APP_COLLECT_TDS_FREQ_REPORT_STRU = 
{
    TRRC_APP_COLLECT_TDS_FREQ_REPORT_STRU_ALARMID,     TRRC_APP_COLLECT_TDS_FREQ_REPORT_STRU_SUBEVENT,     100,     50,
    {
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[2];
} g_TRRC_APP_CONFIG_PCH_CELL_INFO_REPORT_STRU = 
{
    TRRC_APP_CONFIG_PCH_CELL_INFO_REPORT_STRU_ALARMID,     TRRC_APP_CONFIG_PCH_CELL_INFO_REPORT_STRU_SUBEVENT,     84,     2,
    {
    {FIELD_TYPE_UINT, 4},
    {0xA00 | FIELD_TYPE_CLASSARRAY, PCH_CELL_INFO_REPORT_STRU_ID},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[4];
} g_TRRC_CHR_RRM_RESOURCE_CHECK_INFO_LIST_STRU = 
{
    TRRC_CHR_RRM_RESOURCE_CHECK_INFO_LIST_STRU_ALARMID,     TRRC_CHR_RRM_RESOURCE_CHECK_INFO_LIST_STRU_SUBEVENT,     1364,     4,
    {
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {0xA00 | FIELD_TYPE_CLASSARRAY, TRRC_CHR_RRM_RESOURCE_CHECK_INFO_STRU_ID},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[6];
} g_TRRC_CS_CALL_AIRMSG_INFO_STRU = 
{
    TRRC_CS_CALL_AIRMSG_INFO_STRU_ALARMID,     TRRC_CS_CALL_AIRMSG_INFO_STRU_SUBEVENT,     36,     6,
    {
    {FIELD_TYPE_CLASS, TRRC_APP_STATE_INFO_STRU_ID},
    {FIELD_TYPE_CLASS, TRRC_APP_CS_RELEASE_CELL_INFO_STRU_ID},
    {FIELD_TYPE_CLASS, TRRC_CS_CALL_MM_INFO_STRU_ID},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[12];
} g_TRRC_CS_CALL_CONN_REQ_INFO_STRU = 
{
    TRRC_CS_CALL_CONN_REQ_INFO_STRU_ALARMID,     TRRC_CS_CALL_CONN_REQ_INFO_STRU_SUBEVENT,     48,     12,
    {
    {FIELD_TYPE_CLASS, TRRC_APP_STATE_INFO_STRU_ID},
    {FIELD_TYPE_CLASS, TRRC_APP_CS_RELEASE_CELL_INFO_STRU_ID},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_ENUM, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_ARRAY, 2},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[12];
} g_TRRC_CS_CALL_EST_CNF_INFO_STRU = 
{
    TRRC_CS_CALL_EST_CNF_INFO_STRU_ALARMID,     TRRC_CS_CALL_EST_CNF_INFO_STRU_SUBEVENT,     36,     12,
    {
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_ENUM, 1},
    {FIELD_TYPE_INT, 1},
    {FIELD_TYPE_ARRAY, 2},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_ENUM, 4},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[13];
} g_TRRC_OOS_INFO_STRU = 
{
    TRRC_OOS_INFO_STRU_ALARMID,     TRRC_OOS_INFO_STRU_SUBEVENT,     40,     13,
    {
    {0x200 | FIELD_TYPE_ENUMARRAY, 1},
    {FIELD_TYPE_VARCHAR, 2},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_VARCHAR, 2},
    {FIELD_TYPE_UINT, 4},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[13];
} g_TRRC_OUT_OF_SYNC_CELL_UPDATE_INFO_STRU = 
{
    TRRC_OUT_OF_SYNC_CELL_UPDATE_INFO_STRU_ALARMID,     TRRC_OUT_OF_SYNC_CELL_UPDATE_INFO_STRU_SUBEVENT,     32,     13,
    {
    {FIELD_TYPE_INT, 1},
    {FIELD_TYPE_INT, 1},
    {FIELD_TYPE_ENUM, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[6];
} g_TRRC_STATISTIC_INFO_COLLECTION = 
{
    TRRC_STATISTIC_INFO_COLLECTION_EVENTID,     0,     336,     6,
    {
    {FIELD_TYPE_CLASS, TRRC_OUT_OF_SYNC_CELL_UPDATE_INFO_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, TRRC_APP_COLLECT_TDS_FREQ_REPORT_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, TRRC_CS_CALL_EST_CNF_INFO_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, TRRC_CS_CALL_CONN_REQ_INFO_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, TRRC_CS_CALL_AIRMSG_INFO_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, TRRC_APP_CONFIG_PCH_CELL_INFO_REPORT_STRU_SUBEVENT},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[3];
} g_WAS_NET_WORK_FEATURE_CHR_RPT_STRU = 
{
    WAS_NET_WORK_FEATURE_CHR_RPT_STRU_ALARMID,     WAS_NET_WORK_FEATURE_CHR_RPT_STRU_SUBEVENT,     36,     3,
    {
    {FIELD_TYPE_ENUM, 1},
    {FIELD_TYPE_ARRAY, 3},
    {FIELD_TYPE_CLASS, WAS_MNTN_ERR_LOG_SERV_CELL_WHOLE_INFO_STRU_ID},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[3];
} g_WAS_RADIO_RESOURCE_CHECK_CHR_RPT_STRU = 
{
    WAS_RADIO_RESOURCE_CHECK_CHR_RPT_STRU_ALARMID,     WAS_RADIO_RESOURCE_CHECK_CHR_RPT_STRU_SUBEVENT,     208,     3,
    {
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_ARRAY, 3},
    {0x300 | FIELD_TYPE_CLASSARRAY, WAS_MNTN_ERR_LOG_RESOURCE_CHECK_EXCEPTION_INFO_STRU_ID},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[3];
} g_WAS_RRC_ACCESS_LONG_CHR_RPT_STRU = 
{
    WAS_RRC_ACCESS_LONG_CHR_RPT_STRU_ALARMID,     WAS_RRC_ACCESS_LONG_CHR_RPT_STRU_SUBEVENT,     184,     3,
    {
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_ARRAY, 2},
    {0x500 | FIELD_TYPE_CLASSARRAY, WAS_MNTN_ERR_LOG_ACCESS_LONG_INFO_STRU_ID},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[6];
} g_WAS_RRC_STATE_LAST_TIME_CHR_RPT_STRU = 
{
    WAS_RRC_STATE_LAST_TIME_CHR_RPT_STRU_ALARMID,     WAS_RRC_STATE_LAST_TIME_CHR_RPT_STRU_SUBEVENT,     24,     6,
    {
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[5];
} g_WAS_STATISTIC_INFO_COLLECTION = 
{
    WAS_STATISTIC_INFO_COLLECTION_EVENTID,     0,     732,     5,
    {
    {FIELD_TYPE_CLASS, WAS_RRC_ACCESS_LONG_CHR_RPT_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, WAS_RRC_STATE_LAST_TIME_CHR_RPT_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, WAS_WOOS_SEARCH_SECTION_CHR_RPT_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, WAS_W2W_RESEL_SLOW_CHR_RPT_STRU_SUBEVENT},
    {FIELD_TYPE_CLASS, WAS_NET_WORK_FEATURE_CHR_RPT_STRU_SUBEVENT},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[2];
} g_WAS_W2W_RESEL_SLOW_CHR_RPT_STRU = 
{
    WAS_W2W_RESEL_SLOW_CHR_RPT_STRU_ALARMID,     WAS_W2W_RESEL_SLOW_CHR_RPT_STRU_SUBEVENT,     164,     2,
    {
    {FIELD_TYPE_UINT, 4},
    {0xA00 | FIELD_TYPE_CLASSARRAY, WAS_MNTN_ERR_LOG_W2W_RESEL_SLOW_INFO_STRU_ID},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[3];
} g_WAS_WOOS_SEARCH_SECTION_CHR_RPT_STRU = 
{
    WAS_WOOS_SEARCH_SECTION_CHR_RPT_STRU_ALARMID,     WAS_WOOS_SEARCH_SECTION_CHR_RPT_STRU_SUBEVENT,     324,     3,
    {
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_ARRAY, 3},
    {0x1400 | FIELD_TYPE_CLASSARRAY, WAS_MNTN_ERR_LOG_WOOS_SRCH_SECTION_INFO_STRU_ID},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[3];
} g_CAS_RESOURCE_EXCEPTION_INFO_STRU = 
{
    0,     CAS_RESOURCE_EXCEPTION_INFO_STRU_ID,     8,     3,
    {
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_ENUM, 2},
    {FIELD_TYPE_ARRAY, 2},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[6];
} g_GAS_ERR_LOG_AREA_IDENTIFICATION_STRU = 
{
    0,     GAS_ERR_LOG_AREA_IDENTIFICATION_STRU_ID,     16,     6,
    {
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_ARRAY, 3},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[5];
} g_GAS_ERR_LOG_GSM_CELL_INFO_STRU = 
{
    0,     GAS_ERR_LOG_GSM_CELL_INFO_STRU_ID,     8,     5,
    {
    {FIELD_TYPE_ENUM, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_ARRAY, 2},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[8];
} g_GAS_MNTN_CUSTOM_C1_CELL_INFO_STRU = 
{
    0,     GAS_MNTN_CUSTOM_C1_CELL_INFO_STRU_ID,     16,     8,
    {
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_ARRAY, 1},
    {FIELD_TYPE_INT, 2},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[2];
} g_GAS_MNTN_GSM_CELL_WITH_AREA_IDENTIFY_STRU = 
{
    0,     GAS_MNTN_GSM_CELL_WITH_AREA_IDENTIFY_STRU_ID,     24,     2,
    {
    {FIELD_TYPE_CLASS, GAS_ERR_LOG_GSM_CELL_INFO_STRU_ID},
    {FIELD_TYPE_CLASS, GAS_ERR_LOG_AREA_IDENTIFICATION_STRU_ID},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[3];
} g_GAS_MNTN_RSRC_CHECK_EXCP_TASK_INFO_STRU = 
{
    0,     GAS_MNTN_RSRC_CHECK_EXCP_TASK_INFO_STRU_ID,     34,     3,
    {
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_ARRAY, 1},
    {0x1000 | FIELD_TYPE_CLASSARRAY, GAS_MNTN_RSRC_CHECK_EXCP_TASK_TYPE_STRU_ID},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[1];
} g_GAS_MNTN_RSRC_CHECK_EXCP_TASK_TYPE_STRU = 
{
    0,     GAS_MNTN_RSRC_CHECK_EXCP_TASK_TYPE_STRU_ID,     2,     1,
    {
    {FIELD_TYPE_ENUM, 2},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[2];
} g_GUCNAS_RESOURCE_CHECK_SESSION_INFO_STRU = 
{
    0,     GUCNAS_RESOURCE_CHECK_SESSION_INFO_STRU_ID,     8,     2,
    {
    {FIELD_TYPE_ENUM, 4},
    {FIELD_TYPE_UINT, 4},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[13];
} g_LL2_OM_VOLTE_STAT_INFO_STRU = 
{
    0,     LL2_OM_VOLTE_STAT_INFO_STRU_ID,     24,     13,
    {
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_ENUM, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 2},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[4];
} g_LMAC_OM_PRACH_CONFIG_STRU = 
{
    0,     LMAC_OM_PRACH_CONFIG_STRU_ID,     4,     4,
    {
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[2];
} g_LNAS_OM_ERRLOG_PLMN_ID_STRU = 
{
    0,     LNAS_OM_ERRLOG_PLMN_ID_STRU_ID,     4,     2,
    {
    {FIELD_TYPE_ARRAY, 3},
    {FIELD_TYPE_UINT, 1},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[12];
} g_LNAS_OM_ERRLOG_POSITION_INFO_STRU = 
{
    0,     LNAS_OM_ERRLOG_POSITION_INFO_STRU_ID,     48,     12,
    {
    {FIELD_TYPE_CLASS, LNAS_OM_ERRLOG_PLMN_ID_STRU_ID},
    {FIELD_TYPE_CLASS, LNAS_OM_ERRLOG_TAC_STRU_ID},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[3];
} g_LNAS_OM_ERRLOG_TAC_STRU = 
{
    0,     LNAS_OM_ERRLOG_TAC_STRU_ID,     4,     3,
    {
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_ARRAY, 2},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[12];
} g_LPS_LOW_QUILITY_ABNORMAL_STRU = 
{
    0,     LPS_LOW_QUILITY_ABNORMAL_STRU_ID,     12,     12,
    {
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[6];
} g_LRRC_CHR_DSDS_TASK_TYPE_INFO_STRU = 
{
    0,     LRRC_CHR_DSDS_TASK_TYPE_INFO_STRU_ID,     8,     6,
    {
    {FIELD_TYPE_ENUM, 2},
    {FIELD_TYPE_ENUM, 1},
    {FIELD_TYPE_ENUM, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_ARRAY, 2},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[4];
} g_LRRC_CHR_RRM_RES_CHECK_INFO_STRU = 
{
    0,     LRRC_CHR_RRM_RES_CHECK_INFO_STRU_ID,     72,     4,
    {
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {0x800 | FIELD_TYPE_CLASSARRAY, LRRC_CHR_DSDS_TASK_TYPE_INFO_STRU_ID},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[16];
} g_LRRC_OM_AIR_SIGNAL_INFO_STRU = 
{
    0,     LRRC_OM_AIR_SIGNAL_INFO_STRU_ID,     28,     16,
    {
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_INT, 2},
    {FIELD_TYPE_INT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_INT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_INT, 2},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_INT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_INT, 1},
    {FIELD_TYPE_ENUM, 1},
    {FIELD_TYPE_INT, 1},
    {FIELD_TYPE_UINT, 2},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[3];
} g_LRRC_OM_LAYER_EVENT_INFO_STRU = 
{
    0,     LRRC_OM_LAYER_EVENT_INFO_STRU_ID,     8,     3,
    {
    {FIELD_TYPE_ENUM, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 4},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[18];
} g_LRRC_OM_MEASRPT_INFO = 
{
    0,     LRRC_OM_MEASRPT_INFO_ID,     28,     18,
    {
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_ENUM, 1},
    {FIELD_TYPE_ENUM, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_ENUM, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[9];
} g_LRRC_OM_SCELL_ID = 
{
    0,     LRRC_OM_SCELL_ID_ID,     24,     9,
    {
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_CLASS, LRRC_OM_TAC_STRU_ID},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[3];
} g_LRRC_OM_TAC_STRU = 
{
    0,     LRRC_OM_TAC_STRU_ID,     4,     3,
    {
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_ARRAY, 2},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[6];
} g_LRRC_OM_VOLTE_SINGLE_CALL_INFO_STRU = 
{
    0,     LRRC_OM_VOLTE_SINGLE_CALL_INFO_STRU_ID,     12,     6,
    {
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_CLASS, LRRC_OM_TAC_STRU_ID},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[7];
} g_LRRC_OM_VOLTE_SINGLE_FAULT_INFO_STRU = 
{
    0,     LRRC_OM_VOLTE_SINGLE_FAULT_INFO_STRU_ID,     8,     7,
    {
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_ENUM, 1},
    {FIELD_TYPE_ENUM, 2},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[3];
} g_NAS_MM_LAC_STRU = 
{
    0,     NAS_MM_LAC_STRU_ID,     4,     3,
    {
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_ARRAY, 2},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[2];
} g_NAS_MM_PLMN_ID_STRU = 
{
    0,     NAS_MM_PLMN_ID_STRU_ID,     4,     2,
    {
    {FIELD_TYPE_ARRAY, 3},
    {FIELD_TYPE_UINT, 1},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[3];
} g_NAS_MM_TAC_STRU = 
{
    0,     NAS_MM_TAC_STRU_ID,     4,     3,
    {
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_ARRAY, 2},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[4];
} g_PCH_CELL_INFO_REPORT_STRU = 
{
    0,     PCH_CELL_INFO_REPORT_STRU_ID,     8,     4,
    {
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_ENUM, 1},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_CLASS, T_CellDesc_Tag_ID},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[4];
} g_TAF_SSA_DECODE_FAIL_INFO_STRU = 
{
    0,     TAF_SSA_DECODE_FAIL_INFO_STRU_ID,     8,     4,
    {
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_ARRAY, 1},
    {FIELD_TYPE_UINT, 2},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[5];
} g_TLL2_LMAC_PREAMBLE_SPEC_NOT_MATCH_LOG_STRU = 
{
    0,     TLL2_LMAC_PREAMBLE_SPEC_NOT_MATCH_LOG_STRU_ID,     32,     5,
    {
    {FIELD_TYPE_ENUM, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_CLASS, LRRC_OM_SCELL_ID_ID},
    {FIELD_TYPE_CLASS, LMAC_OM_PRACH_CONFIG_STRU_ID},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[5];
} g_TRRC_APP_CS_RELEASE_CELL_INFO_STRU = 
{
    0,     TRRC_APP_CS_RELEASE_CELL_INFO_STRU_ID,     8,     5,
    {
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_ENUM, 1},
    {FIELD_TYPE_INT, 1},
    {FIELD_TYPE_ARRAY, 2},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[3];
} g_TRRC_APP_STATE_INFO_STRU = 
{
    0,     TRRC_APP_STATE_INFO_STRU_ID,     4,     3,
    {
    {FIELD_TYPE_ENUM, 1},
    {FIELD_TYPE_ENUM, 1},
    {FIELD_TYPE_ENUM, 2},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[4];
} g_TRRC_CHR_DSDS_TASK_TYPE_INFO_STRU = 
{
    0,     TRRC_CHR_DSDS_TASK_TYPE_INFO_STRU_ID,     8,     4,
    {
    {FIELD_TYPE_ENUM, 2},
    {FIELD_TYPE_ENUM, 1},
    {FIELD_TYPE_ENUM, 1},
    {FIELD_TYPE_UINT, 4},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[4];
} g_TRRC_CHR_RRM_RESOURCE_CHECK_INFO_STRU = 
{
    0,     TRRC_CHR_RRM_RESOURCE_CHECK_INFO_STRU_ID,     136,     4,
    {
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {0x1000 | FIELD_TYPE_CLASSARRAY, TRRC_CHR_DSDS_TASK_TYPE_INFO_STRU_ID},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[5];
} g_TRRC_CS_CALL_MM_INFO_STRU = 
{
    0,     TRRC_CS_CALL_MM_INFO_STRU_ID,     12,     5,
    {
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[3];
} g_T_CellDesc_Tag = 
{
    0,     T_CellDesc_Tag_ID,     4,     3,
    {
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_UINT, 1},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[2];
} g_WAS_MNTN_ERR_LOG_ACCESS_LONG_INFO_STRU = 
{
    0,     WAS_MNTN_ERR_LOG_ACCESS_LONG_INFO_STRU_ID,     36,     2,
    {
    {FIELD_TYPE_CLASS, WAS_MNTN_ERR_LOG_SERV_CELL_WHOLE_INFO_STRU_ID},
    {FIELD_TYPE_CLASS, WAS_MNTN_ERR_LOG_ACCESS_POWER_INFO_STRU_ID},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[4];
} g_WAS_MNTN_ERR_LOG_ACCESS_POWER_INFO_STRU = 
{
    0,     WAS_MNTN_ERR_LOG_ACCESS_POWER_INFO_STRU_ID,     4,     4,
    {
    {FIELD_TYPE_INT, 1},
    {FIELD_TYPE_INT, 1},
    {FIELD_TYPE_INT, 1},
    {FIELD_TYPE_VARCHAR, 1},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[2];
} g_WAS_MNTN_ERR_LOG_RESOURCE_CHECK_EXCEPTION_INFO_STRU = 
{
    0,     WAS_MNTN_ERR_LOG_RESOURCE_CHECK_EXCEPTION_INFO_STRU_ID,     68,     2,
    {
    {FIELD_TYPE_UINT, 4},
    {0x1000 | FIELD_TYPE_CLASSARRAY, WAS_MNTN_ERR_LOG_RRM_PS_TASK_TYPE_INFO_STRU_ID},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[2];
} g_WAS_MNTN_ERR_LOG_RRM_PS_TASK_TYPE_INFO_STRU = 
{
    0,     WAS_MNTN_ERR_LOG_RRM_PS_TASK_TYPE_INFO_STRU_ID,     4,     2,
    {
    {FIELD_TYPE_ARRAY, 2},
    {FIELD_TYPE_ENUM, 2},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[8];
} g_WAS_MNTN_ERR_LOG_SERV_CELL_INFO_STRU = 
{
    0,     WAS_MNTN_ERR_LOG_SERV_CELL_INFO_STRU_ID,     20,     8,
    {
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_ARRAY, 3},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[6];
} g_WAS_MNTN_ERR_LOG_SERV_CELL_WHOLE_INFO_STRU = 
{
    0,     WAS_MNTN_ERR_LOG_SERV_CELL_WHOLE_INFO_STRU_ID,     32,     6,
    {
    {FIELD_TYPE_ENUM, 1},
    {FIELD_TYPE_ARRAY, 3},
    {FIELD_TYPE_CLASS, WAS_MNTN_ERR_LOG_SERV_CELL_INFO_STRU_ID},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_INT, 2},
    {FIELD_TYPE_INT, 2},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[6];
} g_WAS_MNTN_ERR_LOG_W2W_RESEL_SLOW_INFO_STRU = 
{
    0,     WAS_MNTN_ERR_LOG_W2W_RESEL_SLOW_INFO_STRU_ID,     16,     6,
    {
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 2},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_ENUM, 1},
    {FIELD_TYPE_ARRAY, 3},
    }
};
const struct
{
    VOS_UINT16          EventID;
    VOS_UINT16          StructID;
    VOS_UINT16          StructSize;
    VOS_UINT16          FieldCount;
    FIELD_DESC          Fields[6];
} g_WAS_MNTN_ERR_LOG_WOOS_SRCH_SECTION_INFO_STRU = 
{
    0,     WAS_MNTN_ERR_LOG_WOOS_SRCH_SECTION_INFO_STRU_ID,     16,     6,
    {
    {FIELD_TYPE_ENUM, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_UINT, 4},
    {FIELD_TYPE_ENUM, 1},
    {FIELD_TYPE_UINT, 1},
    {FIELD_TYPE_ARRAY, 2},
    }
};
const VOS_VOID * const g_FaultStructDesc[] = 
{
    (const VOS_VOID *) &g_CAS_1X_RADIO_RESOURCE_CHECK_CHR_RPT_STRU,
    (const VOS_VOID *) &g_CAS_HRPD_RADIO_RESOURCE_CHECK_CHR_RPT_STRU,
    (const VOS_VOID *) &g_CTTF_RADIO_RESOURCE_CHECK_CHR_DIRECT_RPT_STRU,
    (const VOS_VOID *) &g_GAS_CUSTOM_C1_CELL_CHR_RPT_STRU,
    (const VOS_VOID *) &g_GAS_ERR_LOG_EVT_NET_WORK_FEATURE_RPT_STRU,
    (const VOS_VOID *) &g_GAS_NOT_SUPP_BSS_PAGING_COOR_CHR_RPT_STRU,
    (const VOS_VOID *) &g_GAS_RADIO_RESOURCE_CHECK_CHR_RPT_STRU,
    (const VOS_VOID *) &g_GUCNAS_RADIO_RESOURCE_CHECK_CHR_RPT_STRU,
    (const VOS_VOID *) &g_GUCNAS_SS_DECODE_EXCEPT_CHR_RPT_STRU,
    (const VOS_VOID *) &g_LMAC_OM_PREAMBLE_SPEC_NOT_MATCH_INFO_STRU,
    (const VOS_VOID *) &g_LNAS_EMM_ERR_INFO_3440_TIMEOUT_DO_NOT_REL_STRU,
    (const VOS_VOID *) &g_LNAS_EMM_ERR_INFO_ATT_FAIL_ESM_NEED_DISABLE_LTE_STRU,
    (const VOS_VOID *) &g_LNAS_EMM_ERR_INFO_AUTH_REJ_OPT_STRU,
    (const VOS_VOID *) &g_LNAS_EMM_ERR_INFO_CNMSG_DECODE_FAIL_STRU,
    (const VOS_VOID *) &g_LNAS_EMM_ERR_INFO_CSFB_TAU_RCV_MT_DETACH_STRU,
    (const VOS_VOID *) &g_LNAS_EMM_ERR_INFO_DETACH_NO_RF_STRU,
    (const VOS_VOID *) &g_LNAS_EMM_ERR_INFO_DSDS_BUFFER_NO_RF_TAU_REQ_STRU,
    (const VOS_VOID *) &g_LNAS_EMM_ERR_INFO_DSDS_NO_RF_TAU_PUNISH_STRU,
    (const VOS_VOID *) &g_LNAS_EMM_ERR_INFO_DSDS_RF_RECOVER_RETRY_STRU,
    (const VOS_VOID *) &g_LNAS_EMM_ERR_INFO_DSDS_RRM_RF_CHECKIN_STRU,
    (const VOS_VOID *) &g_LNAS_EMM_ERR_INFO_EMC_BERER_CN_REJ_ANYCELL_SRCH_STRU,
    (const VOS_VOID *) &g_LNAS_EMM_ERR_INFO_EMC_DATA_REQ_TAU_STRU,
    (const VOS_VOID *) &g_LNAS_EMM_ERR_INFO_GRADUAL_FORBIDDEN_OPTIMIZE_STRU,
    (const VOS_VOID *) &g_LNAS_EMM_ERR_INFO_IMPROVE_CALL_SUCC_RATIO_STRU,
    (const VOS_VOID *) &g_LNAS_EMM_ERR_INFO_IMS_BEARER_WITH_CN_MOD_CONFLICT_STRU,
    (const VOS_VOID *) &g_LNAS_EMM_ERR_INFO_LANZHOU_CSFB_OPTIMIZE_STRU,
    (const VOS_VOID *) &g_LNAS_EMM_ERR_INFO_LOAD_BALANCE_STRU,
    (const VOS_VOID *) &g_LNAS_EMM_ERR_INFO_LOCAL_DETACH_STRU,
    (const VOS_VOID *) &g_LNAS_EMM_ERR_INFO_LTE_FAKE_NODEB_STRU,
    (const VOS_VOID *) &g_LNAS_EMM_ERR_INFO_MMC_REL_DRGINIT_STRU,
    (const VOS_VOID *) &g_LNAS_EMM_ERR_INFO_MO_BAR_ATTAMPT_STRU,
    (const VOS_VOID *) &g_LNAS_EMM_ERR_INFO_MT_DETACH_OPTIMIZE_STRU,
    (const VOS_VOID *) &g_LNAS_EMM_ERR_INFO_MT_SERVICE_RETRY_STRU,
    (const VOS_VOID *) &g_LNAS_EMM_ERR_INFO_NO_RAU_WITH_TAU_STRU,
    (const VOS_VOID *) &g_LNAS_EMM_ERR_INFO_PERIODIC_TAU_WITH_CAUSE_STRU,
    (const VOS_VOID *) &g_LNAS_EMM_ERR_INFO_SMC_FAIL_STRU,
    (const VOS_VOID *) &g_LNAS_EMM_ERR_INFO_START_3402_ADD_FORB_LIST_STRU,
    (const VOS_VOID *) &g_LNAS_EMM_ERR_INFO_T3402_DEACTIVED_STRU,
    (const VOS_VOID *) &g_LNAS_EMM_ERR_INFO_TAU_EST_WITH_CELL_SEARCHING_OPT_STRU,
    (const VOS_VOID *) &g_LNAS_EMM_ERR_INFO_TAU_WITH_CONN_REL_DO_NOT_WAIT_3411_TIMEOUT_STRU,
    (const VOS_VOID *) &g_LNAS_EMM_ERR_INFO_VOLTE_WITH_TA_CHANGE_STRU,
    (const VOS_VOID *) &g_LNAS_ESM_ERR_INFO_CNMSG_DECODE_FAIL_STRU,
    (const VOS_VOID *) &g_LNAS_ESM_ERR_INFO_ESM_MSG_RETRANSMITE_STRU,
    (const VOS_VOID *) &g_LNAS_ESM_ERR_INFO_SWITCH_APN_STRU,
    (const VOS_VOID *) &g_LNAS_IMSA_ERR_INFO_DSDS_SMS_RF_OCCUPY_STRU,
    (const VOS_VOID *) &g_LNAS_IMSA_ERR_INFO_DSDS_WAIT_BEAR_REL_TIMEOUT_STRU,
    (const VOS_VOID *) &g_LNAS_IMSA_ERR_INFO_EMC_TCALL_TIMEOUT_STRU,
    (const VOS_VOID *) &g_LNAS_IMSA_ERR_INFO_HANDOVER_INITIAL_PDN_CONN_STRU,
    (const VOS_VOID *) &g_LNAS_IMSA_ERR_INFO_REG_REJ_WAIT_RECOVERY_STRU,
    (const VOS_VOID *) &g_LNAS_IMSA_ERR_INFO_WAIT_RETRY_START_SWITCH_STRU,
    (const VOS_VOID *) &g_LNAS_OM_ERRLOG_CSS_BAND_LIST_INFO_STRU,
    (const VOS_VOID *) &g_LPS_OM_VOLTE_FAULT_AUTOAN_INFO_STRU,
    (const VOS_VOID *) &g_LPS_OM_VOLTE_GENERAL_STAT_INFO_STRU,
    (const VOS_VOID *) &g_LRRC_CHR_RRM_RES_CHECK_INFO_LIST_STRU,
    (const VOS_VOID *) &g_LRRC_OM_UE_CAP_FALL_REPORT_STRU,
    (const VOS_VOID *) &g_LRRC_OM_USER_PLANE_ERR_REL_REPORT_STRU,
    (const VOS_VOID *) &g_TDS_OOS_INFO_REPORT,
    (const VOS_VOID *) &g_TLL2_OOS_INFO_STRU,
    (const VOS_VOID *) &g_TRRC_APP_COLLECT_TDS_FREQ_REPORT_STRU,
    (const VOS_VOID *) &g_TRRC_APP_CONFIG_PCH_CELL_INFO_REPORT_STRU,
    (const VOS_VOID *) &g_TRRC_CHR_RRM_RESOURCE_CHECK_INFO_LIST_STRU,
    (const VOS_VOID *) &g_TRRC_CS_CALL_AIRMSG_INFO_STRU,
    (const VOS_VOID *) &g_TRRC_CS_CALL_CONN_REQ_INFO_STRU,
    (const VOS_VOID *) &g_TRRC_CS_CALL_EST_CNF_INFO_STRU,
    (const VOS_VOID *) &g_TRRC_OOS_INFO_STRU,
    (const VOS_VOID *) &g_TRRC_OUT_OF_SYNC_CELL_UPDATE_INFO_STRU,
    (const VOS_VOID *) &g_WAS_NET_WORK_FEATURE_CHR_RPT_STRU,
    (const VOS_VOID *) &g_WAS_RADIO_RESOURCE_CHECK_CHR_RPT_STRU,
    (const VOS_VOID *) &g_WAS_RRC_ACCESS_LONG_CHR_RPT_STRU,
    (const VOS_VOID *) &g_WAS_RRC_STATE_LAST_TIME_CHR_RPT_STRU,
    (const VOS_VOID *) &g_WAS_W2W_RESEL_SLOW_CHR_RPT_STRU,
    (const VOS_VOID *) &g_WAS_WOOS_SEARCH_SECTION_CHR_RPT_STRU,
    (const VOS_VOID *) &g_CAS_RESOURCE_EXCEPTION_INFO_STRU,
    (const VOS_VOID *) &g_GAS_ERR_LOG_AREA_IDENTIFICATION_STRU,
    (const VOS_VOID *) &g_GAS_ERR_LOG_GSM_CELL_INFO_STRU,
    (const VOS_VOID *) &g_GAS_MNTN_CUSTOM_C1_CELL_INFO_STRU,
    (const VOS_VOID *) &g_GAS_MNTN_GSM_CELL_WITH_AREA_IDENTIFY_STRU,
    (const VOS_VOID *) &g_GAS_MNTN_RSRC_CHECK_EXCP_TASK_INFO_STRU,
    (const VOS_VOID *) &g_GAS_MNTN_RSRC_CHECK_EXCP_TASK_TYPE_STRU,
    (const VOS_VOID *) &g_GUCNAS_RESOURCE_CHECK_SESSION_INFO_STRU,
    (const VOS_VOID *) &g_LL2_OM_VOLTE_STAT_INFO_STRU,
    (const VOS_VOID *) &g_LMAC_OM_PRACH_CONFIG_STRU,
    (const VOS_VOID *) &g_LNAS_OM_ERRLOG_PLMN_ID_STRU,
    (const VOS_VOID *) &g_LNAS_OM_ERRLOG_POSITION_INFO_STRU,
    (const VOS_VOID *) &g_LNAS_OM_ERRLOG_TAC_STRU,
    (const VOS_VOID *) &g_LPS_LOW_QUILITY_ABNORMAL_STRU,
    (const VOS_VOID *) &g_LRRC_CHR_DSDS_TASK_TYPE_INFO_STRU,
    (const VOS_VOID *) &g_LRRC_CHR_RRM_RES_CHECK_INFO_STRU,
    (const VOS_VOID *) &g_LRRC_OM_AIR_SIGNAL_INFO_STRU,
    (const VOS_VOID *) &g_LRRC_OM_LAYER_EVENT_INFO_STRU,
    (const VOS_VOID *) &g_LRRC_OM_MEASRPT_INFO,
    (const VOS_VOID *) &g_LRRC_OM_SCELL_ID,
    (const VOS_VOID *) &g_LRRC_OM_TAC_STRU,
    (const VOS_VOID *) &g_LRRC_OM_VOLTE_SINGLE_CALL_INFO_STRU,
    (const VOS_VOID *) &g_LRRC_OM_VOLTE_SINGLE_FAULT_INFO_STRU,
    (const VOS_VOID *) &g_NAS_MM_LAC_STRU,
    (const VOS_VOID *) &g_NAS_MM_PLMN_ID_STRU,
    (const VOS_VOID *) &g_NAS_MM_TAC_STRU,
    (const VOS_VOID *) &g_PCH_CELL_INFO_REPORT_STRU,
    (const VOS_VOID *) &g_TAF_SSA_DECODE_FAIL_INFO_STRU,
    (const VOS_VOID *) &g_TLL2_LMAC_PREAMBLE_SPEC_NOT_MATCH_LOG_STRU,
    (const VOS_VOID *) &g_TRRC_APP_CS_RELEASE_CELL_INFO_STRU,
    (const VOS_VOID *) &g_TRRC_APP_STATE_INFO_STRU,
    (const VOS_VOID *) &g_TRRC_CHR_DSDS_TASK_TYPE_INFO_STRU,
    (const VOS_VOID *) &g_TRRC_CHR_RRM_RESOURCE_CHECK_INFO_STRU,
    (const VOS_VOID *) &g_TRRC_CS_CALL_MM_INFO_STRU,
    (const VOS_VOID *) &g_T_CellDesc_Tag,
    (const VOS_VOID *) &g_WAS_MNTN_ERR_LOG_ACCESS_LONG_INFO_STRU,
    (const VOS_VOID *) &g_WAS_MNTN_ERR_LOG_ACCESS_POWER_INFO_STRU,
    (const VOS_VOID *) &g_WAS_MNTN_ERR_LOG_RESOURCE_CHECK_EXCEPTION_INFO_STRU,
    (const VOS_VOID *) &g_WAS_MNTN_ERR_LOG_RRM_PS_TASK_TYPE_INFO_STRU,
    (const VOS_VOID *) &g_WAS_MNTN_ERR_LOG_SERV_CELL_INFO_STRU,
    (const VOS_VOID *) &g_WAS_MNTN_ERR_LOG_SERV_CELL_WHOLE_INFO_STRU,
    (const VOS_VOID *) &g_WAS_MNTN_ERR_LOG_W2W_RESEL_SLOW_INFO_STRU,
    (const VOS_VOID *) &g_WAS_MNTN_ERR_LOG_WOOS_SRCH_SECTION_INFO_STRU,
};
const VOS_UINT32 g_FaultStructDescCount = sizeof(g_FaultStructDesc) / sizeof(g_FaultStructDesc[0]);
const VOS_VOID * const g_EventStructDesc[] = 
{
    (const VOS_VOID *) &g_GAS_STATISTIC_INFO_COLLECTION,
    (const VOS_VOID *) &g_GUCNAS_STATISTIC_INFO_COLLECTION,
    (const VOS_VOID *) &g_LL2_STATISTIC_INFO_COLLECTION,
    (const VOS_VOID *) &g_LNAS_STATISTIC_INFO_COLLECTION,
    (const VOS_VOID *) &g_LPS_VOLTE_STAT_IND,
    (const VOS_VOID *) &g_LRRC_STATISTIC1_INFO_COLLECTION,
    (const VOS_VOID *) &g_LRRC_VOLTE_FAULT_AUTOAN_IND,
    (const VOS_VOID *) &g_PS_RADIO_RESOURCE_CHECK,
    (const VOS_VOID *) &g_TRRC_STATISTIC_INFO_COLLECTION,
    (const VOS_VOID *) &g_WAS_STATISTIC_INFO_COLLECTION,
};
const VOS_UINT32 g_EventStructDescCount = sizeof(g_EventStructDesc) / sizeof(g_EventStructDesc[0]);
