/* MD5: 53e23a12099fff70976f07cba435e248*/
#if !defined(__PRODUCT_CONFIG_PAM_H__)
#define __PRODUCT_CONFIG_PAM_H__

#ifndef BBP_MASTER_NONE
#define BBP_MASTER_NONE 0 
#endif 

#ifndef BBP_MASTER_V8R1
#define BBP_MASTER_V8R1 1 
#endif 

#ifndef BBP_MASTER_V7R5
#define BBP_MASTER_V7R5 2 
#endif 

#ifndef BBP_MASTER_V8R5
#define BBP_MASTER_V8R5 3 
#endif 

#ifndef BBP_MASTER_K3V6
#define BBP_MASTER_K3V6 4 
#endif 

#ifndef BBP_MASTER_KIRIN970
#define BBP_MASTER_KIRIN970 5 
#endif 

#ifndef FEATURE_BBP_MASTER_VER
#define FEATURE_BBP_MASTER_VER (BBP_MASTER_KIRIN970) 
#endif 

#ifndef BBP_MASTER_ES
#define BBP_MASTER_ES 0 
#endif 

#ifndef BBP_MASTER_CS
#define BBP_MASTER_CS 1 
#endif 

#ifdef CHIP_TYPE_CS 
#ifndef BBP_MASTER_CHIP_TYPE
#define BBP_MASTER_CHIP_TYPE BBP_MASTER_CS 
#endif 

#else
#ifndef BBP_MASTER_CHIP_TYPE
#define BBP_MASTER_CHIP_TYPE BBP_MASTER_ES 
#endif 

#endif
#ifndef FEATURE_POWER_TIMER
#define FEATURE_POWER_TIMER FEATURE_ON 
#endif 

#ifndef FEATURE_UE_UICC_MULTI_APP_SUPPORT
#define FEATURE_UE_UICC_MULTI_APP_SUPPORT FEATURE_ON 
#endif 

#ifndef FEATURE_VSIM
#define FEATURE_VSIM FEATURE_ON 
#endif 

#ifndef FEATURE_GUC_BBP_TRIG
#define FEATURE_GUC_BBP_TRIG FEATURE_ON 
#endif 

#ifndef FEATURE_GUC_BBP_TRIG_NEWVERSION
#define FEATURE_GUC_BBP_TRIG_NEWVERSION FEATURE_ON 
#endif 

#ifndef FEATURE_GUBBP_HANDSHAKE
#define FEATURE_GUBBP_HANDSHAKE FEATURE_ON 
#endif 

#ifndef FEATURE_GUDRX_NEWVERSION
#define FEATURE_GUDRX_NEWVERSION FEATURE_ON 
#endif 

#ifndef FEATURE_VOS_REDUCE_MEM_CFG
#define FEATURE_VOS_REDUCE_MEM_CFG FEATURE_OFF 
#endif 

#ifndef FEATURE_RTC_TIMER_DBG
#define FEATURE_RTC_TIMER_DBG FEATURE_ON 
#endif 

#ifndef FEATURE_PHONE_SC
#define FEATURE_PHONE_SC FEATURE_ON 
#endif 

#ifndef FEATURE_SC_SEC_UPDATE
#define FEATURE_SC_SEC_UPDATE FEATURE_ON 
#endif 

#ifndef FEATURE_SC_OS_SEC_FILE
#define FEATURE_SC_OS_SEC_FILE FEATURE_OFF 
#endif 

#ifndef FEATURE_SC_DATA_STRUCT_EXTERN
#define FEATURE_SC_DATA_STRUCT_EXTERN FEATURE_OFF 
#endif 

#ifndef FEATURE_SC_NETWORK_UPDATE
#define FEATURE_SC_NETWORK_UPDATE FEATURE_OFF 
#endif 

#ifndef FEATURE_VSIM_ICC_SEC_CHANNEL
#define FEATURE_VSIM_ICC_SEC_CHANNEL FEATURE_ON 
#endif 

#ifndef FEATURE_BOSTON_AFTER_FEATURE
#define FEATURE_BOSTON_AFTER_FEATURE FEATURE_ON 
#endif 

#ifndef FEATURE_BOSTON_ONLY_FEATURE
#define FEATURE_BOSTON_ONLY_FEATURE FEATURE_ON 
#endif 

#endif /*__PRODUCT_CONFIG_H__*/ 
